import AppKit

// Watches the system pasteboard and keeps the last N items (FIFO, capped
// by config, default 50). Text is stored inline in clipboard.json, images
// as PNG files next to it. Passwords are skipped via the standard
// transient/concealed pasteboard markers.
final class ClipboardManager {
    static let shared = ClipboardManager()

    enum Content: Codable, Equatable {
        case text(String)
        case imageFile(String)   // file name inside clipboard-images/
    }

    struct Item: Codable, Equatable, Identifiable {
        let id: String
        let content: Content
        let date: Date
        let sourceApp: String?
    }

    private(set) var items: [Item] = []
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private let saveQueue = DispatchQueue(label: "bolt.clipboard")

    // Set briefly when we put something on the pasteboard ourselves so we
    // don't re-record our own pastes.
    var ignoreNextChange = false

    private init() {
        load()
    }

    func start() {
        guard AppConfig.shared.clipboardHistoryEnabled else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Respect password-manager markers (nspasteboard.org conventions).
        let skipTypes = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        let types = pb.types?.map(\.rawValue) ?? []
        if types.contains(where: { skipTypes.contains($0) }) { return }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        if let text = pb.string(forType: .string) {
            let trimmedProbe = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmedProbe.isEmpty else { return }
            record(Content.text(text), source: source)
        } else if let image = NSImage(pasteboard: pb) {
            guard let png = pngData(from: image) else { return }
            let name = UUID().uuidString + ".png"
            let url = AppPaths.clipboardImagesDir.appendingPathComponent(name)
            do {
                try png.write(to: url)
                record(Content.imageFile(name), source: source)
            } catch {
                NSLog("Bolt: could not store clipboard image: \(error)")
            }
        }
    }

    private func record(_ content: Content, source: String?) {
        // Skip if identical to the most recent entry.
        if let latest = items.first, latest.content == content { return }

        // If the same content exists deeper in history, move it to the top
        // instead of duplicating.
        if let existingIndex = items.firstIndex(where: { $0.content == content }) {
            items.remove(at: existingIndex)
        }

        let item = Item(id: UUID().uuidString, content: content, date: Date(), sourceApp: source)
        items.insert(item, at: 0)

        // FIFO cap: evict the oldest once over capacity.
        let cap = max(1, AppConfig.shared.clipboardCapacity)
        while items.count > cap {
            let evicted = items.removeLast()
            deleteBackingFile(of: evicted)
        }
        save()
    }

    func delete(id: String) {
        if let idx = items.firstIndex(where: { $0.id == id }) {
            deleteBackingFile(of: items[idx])
            items.remove(at: idx)
            save()
        }
    }

    func clearAll() {
        for item in items { deleteBackingFile(of: item) }
        items = []
        save()
    }

    private func deleteBackingFile(of item: Item) {
        if case .imageFile(let name) = item.content {
            try? FileManager.default.removeItem(
                at: AppPaths.clipboardImagesDir.appendingPathComponent(name))
        }
    }

    func image(for item: Item) -> NSImage? {
        guard case .imageFile(let name) = item.content else { return nil }
        return NSImage(contentsOf: AppPaths.clipboardImagesDir.appendingPathComponent(name))
    }

    private func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    // MARK: persistence

    private func load() {
        guard let data = try? Data(contentsOf: AppPaths.clipboardFile),
              let decoded = try? JSONDecoder().decode([Item].self, from: data) else { return }
        items = decoded
    }

    private func save() {
        let snapshot = items
        saveQueue.async {
            if let data = try? JSONEncoder().encode(snapshot) {
                try? data.write(to: AppPaths.clipboardFile)
            }
        }
    }
}
