// Curated emoji set with searchable names. Names double as keywords, so
// "laugh", "rocket", "check" all hit. Extend freely.
enum EmojiData {
    struct Entry {
        let char: String
        let name: String
    }

    static let all: [Entry] = [
        // Smileys
        Entry(char: "😀", name: "grinning face smile happy"),
        Entry(char: "😄", name: "smile happy grin laughing eyes"),
        Entry(char: "😁", name: "beaming grin teeth"),
        Entry(char: "😂", name: "joy laugh tears funny lol"),
        Entry(char: "🤣", name: "rofl rolling laughing lol"),
        Entry(char: "😅", name: "sweat smile nervous laugh"),
        Entry(char: "😊", name: "blush smile happy warm"),
        Entry(char: "🙂", name: "slight smile fine"),
        Entry(char: "😉", name: "wink flirt"),
        Entry(char: "😍", name: "heart eyes love adore"),
        Entry(char: "🥰", name: "smiling hearts love adore"),
        Entry(char: "😘", name: "kiss blow love"),
        Entry(char: "😎", name: "cool sunglasses"),
        Entry(char: "🤩", name: "star struck starstruck wow excited"),
        Entry(char: "🥳", name: "party celebrate birthday hat"),
        Entry(char: "😏", name: "smirk sly"),
        Entry(char: "😐", name: "neutral meh"),
        Entry(char: "😑", name: "expressionless blank"),
        Entry(char: "🙄", name: "eye roll eyeroll annoyed"),
        Entry(char: "😬", name: "grimace awkward cringe"),
        Entry(char: "😴", name: "sleep zzz tired"),
        Entry(char: "🥱", name: "yawn tired bored"),
        Entry(char: "😪", name: "sleepy tired"),
        Entry(char: "😷", name: "mask sick ill"),
        Entry(char: "🤒", name: "thermometer sick fever"),
        Entry(char: "🤕", name: "bandage injured hurt"),
        Entry(char: "🤢", name: "nauseated sick green"),
        Entry(char: "🤮", name: "vomit puke sick"),
        Entry(char: "🤧", name: "sneeze tissue sick"),
        Entry(char: "🥴", name: "woozy drunk dizzy"),
        Entry(char: "😵", name: "dizzy knocked out"),
        Entry(char: "🤯", name: "mind blown exploding head shocked"),
        Entry(char: "🤔", name: "thinking hmm consider"),
        Entry(char: "🤨", name: "raised eyebrow skeptical suspicious"),
        Entry(char: "😳", name: "flushed embarrassed blush shocked"),
        Entry(char: "🥺", name: "pleading puppy eyes beg cute"),
        Entry(char: "😢", name: "cry sad tear"),
        Entry(char: "😭", name: "sob crying loud sad bawling"),
        Entry(char: "😤", name: "huff frustrated steam triumph"),
        Entry(char: "😠", name: "angry mad"),
        Entry(char: "😡", name: "rage furious red angry"),
        Entry(char: "🤬", name: "swearing cursing angry symbols"),
        Entry(char: "😱", name: "scream fear shocked horror"),
        Entry(char: "😨", name: "fearful scared"),
        Entry(char: "😰", name: "anxious sweat nervous"),
        Entry(char: "😥", name: "sad relieved disappointed"),
        Entry(char: "🫠", name: "melting face embarrassed hot"),
        Entry(char: "🙃", name: "upside down silly sarcasm"),
        Entry(char: "🫡", name: "salute respect yes sir"),
        Entry(char: "🤗", name: "hug hugging warm"),
        Entry(char: "🤫", name: "shush quiet secret"),
        Entry(char: "🤭", name: "giggle hand over mouth oops"),
        Entry(char: "🧐", name: "monocle inspect fancy"),
        Entry(char: "🤓", name: "nerd glasses geek"),
        Entry(char: "😇", name: "innocent angel halo"),
        Entry(char: "🤠", name: "cowboy hat yeehaw"),
        Entry(char: "🤥", name: "lying pinocchio nose"),
        Entry(char: "😈", name: "devil smiling imp evil purple"),
        Entry(char: "👿", name: "angry devil imp"),
        Entry(char: "🤡", name: "clown joker"),
        Entry(char: "💀", name: "skull dead death"),
        Entry(char: "👻", name: "ghost boo spooky halloween"),
        Entry(char: "👽", name: "alien ufo"),
        Entry(char: "🤖", name: "robot bot ai"),
        Entry(char: "💩", name: "poop pile of poo"),
        // Gestures and body
        Entry(char: "👍", name: "thumbs up like yes approve ok"),
        Entry(char: "👎", name: "thumbs down dislike no"),
        Entry(char: "👌", name: "ok okay perfect"),
        Entry(char: "🤌", name: "pinched fingers chef italian"),
        Entry(char: "✌️", name: "peace victory two"),
        Entry(char: "🤞", name: "fingers crossed luck hope"),
        Entry(char: "🤟", name: "love you gesture rock"),
        Entry(char: "🤘", name: "rock on horns metal"),
        Entry(char: "🖖", name: "vulcan spock star trek"),
        Entry(char: "👋", name: "wave hello hi bye goodbye"),
        Entry(char: "🤚", name: "raised back of hand stop"),
        Entry(char: "✋", name: "raised hand stop high five"),
        Entry(char: "🖐️", name: "hand splayed five"),
        Entry(char: "👊", name: "fist bump punch"),
        Entry(char: "✊", name: "raised fist power"),
        Entry(char: "👏", name: "clap applause bravo"),
        Entry(char: "🙌", name: "raised hands praise celebration hooray"),
        Entry(char: "🫶", name: "heart hands love"),
        Entry(char: "🤝", name: "handshake deal agreement"),
        Entry(char: "🙏", name: "pray please thanks folded hands namaste"),
        Entry(char: "💪", name: "muscle strong flex bicep gym"),
        Entry(char: "👈", name: "point left"),
        Entry(char: "👉", name: "point right"),
        Entry(char: "👆", name: "point up"),
        Entry(char: "👇", name: "point down"),
        Entry(char: "☝️", name: "index up one"),
        Entry(char: "✍️", name: "writing hand write"),
        Entry(char: "🤳", name: "selfie phone"),
        Entry(char: "💅", name: "nail polish sassy"),
        Entry(char: "👀", name: "eyes look watching sus"),
        Entry(char: "👁️", name: "eye single"),
        Entry(char: "🧠", name: "brain smart mind"),
        Entry(char: "🦾", name: "mechanical arm bionic strong"),
        Entry(char: "🗣️", name: "speaking head talk announce"),
        // Hearts and symbols
        Entry(char: "❤️", name: "red heart love"),
        Entry(char: "🧡", name: "orange heart"),
        Entry(char: "💛", name: "yellow heart"),
        Entry(char: "💚", name: "green heart"),
        Entry(char: "💙", name: "blue heart"),
        Entry(char: "💜", name: "purple heart"),
        Entry(char: "🖤", name: "black heart"),
        Entry(char: "🤍", name: "white heart"),
        Entry(char: "💔", name: "broken heart sad breakup"),
        Entry(char: "❣️", name: "heart exclamation"),
        Entry(char: "💕", name: "two hearts love"),
        Entry(char: "💖", name: "sparkling heart love"),
        Entry(char: "💗", name: "growing heart"),
        Entry(char: "💯", name: "hundred 100 percent perfect score"),
        Entry(char: "💢", name: "anger symbol"),
        Entry(char: "💥", name: "boom collision explosion bang"),
        Entry(char: "💫", name: "dizzy stars"),
        Entry(char: "💦", name: "sweat droplets water"),
        Entry(char: "💨", name: "dash wind fast gone"),
        Entry(char: "🕳️", name: "hole"),
        Entry(char: "💬", name: "speech bubble chat comment"),
        Entry(char: "💭", name: "thought bubble thinking"),
        Entry(char: "💤", name: "zzz sleep"),
        // Animals
        Entry(char: "🐶", name: "dog puppy pet"),
        Entry(char: "🐱", name: "cat kitten pet"),
        Entry(char: "🐭", name: "mouse"),
        Entry(char: "🐹", name: "hamster"),
        Entry(char: "🐰", name: "rabbit bunny"),
        Entry(char: "🦊", name: "fox"),
        Entry(char: "🐻", name: "bear"),
        Entry(char: "🐼", name: "panda"),
        Entry(char: "🐨", name: "koala"),
        Entry(char: "🐯", name: "tiger face"),
        Entry(char: "🦁", name: "lion"),
        Entry(char: "🐮", name: "cow face"),
        Entry(char: "🐷", name: "pig face"),
        Entry(char: "🐸", name: "frog"),
        Entry(char: "🐵", name: "monkey face"),
        Entry(char: "🙈", name: "see no evil monkey"),
        Entry(char: "🙉", name: "hear no evil monkey"),
        Entry(char: "🙊", name: "speak no evil monkey"),
        Entry(char: "🐔", name: "chicken"),
        Entry(char: "🐧", name: "penguin linux"),
        Entry(char: "🐦", name: "bird tweet"),
        Entry(char: "🦆", name: "duck"),
        Entry(char: "🦅", name: "eagle"),
        Entry(char: "🦉", name: "owl wise"),
        Entry(char: "🐴", name: "horse face"),
        Entry(char: "🦄", name: "unicorn magic"),
        Entry(char: "🐝", name: "bee honeybee"),
        Entry(char: "🦋", name: "butterfly"),
        Entry(char: "🐌", name: "snail slow"),
        Entry(char: "🐢", name: "turtle slow"),
        Entry(char: "🐍", name: "snake python"),
        Entry(char: "🦖", name: "t-rex dinosaur"),
        Entry(char: "🐙", name: "octopus"),
        Entry(char: "🦀", name: "crab rust"),
        Entry(char: "🐠", name: "tropical fish"),
        Entry(char: "🐬", name: "dolphin"),
        Entry(char: "🐳", name: "whale docker"),
        Entry(char: "🦈", name: "shark"),
        Entry(char: "🐘", name: "elephant postgres"),
        Entry(char: "🦒", name: "giraffe"),
        Entry(char: "🐪", name: "camel perl"),
        Entry(char: "🐿️", name: "chipmunk squirrel"),
        Entry(char: "🦔", name: "hedgehog"),
        // Food
        Entry(char: "🍎", name: "apple red fruit"),
        Entry(char: "🍌", name: "banana fruit"),
        Entry(char: "🍇", name: "grapes fruit"),
        Entry(char: "🍓", name: "strawberry fruit"),
        Entry(char: "🍉", name: "watermelon fruit"),
        Entry(char: "🍊", name: "orange tangerine fruit"),
        Entry(char: "🍋", name: "lemon fruit sour"),
        Entry(char: "🍍", name: "pineapple fruit"),
        Entry(char: "🥭", name: "mango fruit"),
        Entry(char: "🥑", name: "avocado"),
        Entry(char: "🍅", name: "tomato"),
        Entry(char: "🌶️", name: "hot pepper chili spicy"),
        Entry(char: "🌽", name: "corn maize"),
        Entry(char: "🥕", name: "carrot vegetable"),
        Entry(char: "🍞", name: "bread loaf"),
        Entry(char: "🧀", name: "cheese"),
        Entry(char: "🍳", name: "egg fried cooking"),
        Entry(char: "🥓", name: "bacon"),
        Entry(char: "🍔", name: "burger hamburger"),
        Entry(char: "🍟", name: "fries french fries"),
        Entry(char: "🍕", name: "pizza slice"),
        Entry(char: "🌭", name: "hot dog"),
        Entry(char: "🌮", name: "taco"),
        Entry(char: "🌯", name: "burrito wrap"),
        Entry(char: "🍜", name: "noodles ramen soup"),
        Entry(char: "🍣", name: "sushi japanese"),
        Entry(char: "🍚", name: "rice bowl"),
        Entry(char: "🍛", name: "curry rice indian"),
        Entry(char: "🍰", name: "cake shortcake dessert"),
        Entry(char: "🎂", name: "birthday cake celebration"),
        Entry(char: "🍩", name: "donut doughnut"),
        Entry(char: "🍪", name: "cookie biscuit"),
        Entry(char: "🍫", name: "chocolate bar"),
        Entry(char: "🍿", name: "popcorn movie"),
        Entry(char: "☕", name: "coffee hot beverage tea"),
        Entry(char: "🍵", name: "tea green teacup"),
        Entry(char: "🧋", name: "boba bubble tea"),
        Entry(char: "🍺", name: "beer mug"),
        Entry(char: "🍻", name: "beers cheers clink"),
        Entry(char: "🍷", name: "wine glass"),
        Entry(char: "🥂", name: "champagne clink cheers toast"),
        Entry(char: "🍸", name: "cocktail martini"),
        // Activities and objects
        Entry(char: "⚽", name: "soccer football ball"),
        Entry(char: "🏀", name: "basketball ball"),
        Entry(char: "🏈", name: "american football"),
        Entry(char: "🎾", name: "tennis ball"),
        Entry(char: "🏏", name: "cricket bat ball"),
        Entry(char: "🏸", name: "badminton"),
        Entry(char: "🥊", name: "boxing glove"),
        Entry(char: "🏆", name: "trophy winner champion"),
        Entry(char: "🥇", name: "gold medal first"),
        Entry(char: "🥈", name: "silver medal second"),
        Entry(char: "🥉", name: "bronze medal third"),
        Entry(char: "🎯", name: "dart target bullseye goal"),
        Entry(char: "🎮", name: "video game controller gaming"),
        Entry(char: "🎲", name: "dice game random"),
        Entry(char: "🧩", name: "puzzle piece jigsaw"),
        Entry(char: "🎸", name: "guitar music rock"),
        Entry(char: "🎹", name: "piano keyboard music"),
        Entry(char: "🥁", name: "drum music"),
        Entry(char: "🎤", name: "microphone sing karaoke"),
        Entry(char: "🎧", name: "headphones music listen"),
        Entry(char: "🎬", name: "clapper movie film action"),
        Entry(char: "🎨", name: "art palette paint design"),
        Entry(char: "🎭", name: "theater masks drama"),
        Entry(char: "🎪", name: "circus tent"),
        Entry(char: "🎉", name: "party popper tada celebrate congrats"),
        Entry(char: "🎊", name: "confetti ball celebrate"),
        Entry(char: "🎈", name: "balloon party"),
        Entry(char: "🎁", name: "gift present wrapped"),
        Entry(char: "🎗️", name: "reminder ribbon"),
        // Travel and places
        Entry(char: "🚗", name: "car automobile red"),
        Entry(char: "🚕", name: "taxi cab"),
        Entry(char: "🚌", name: "bus"),
        Entry(char: "🚓", name: "police car"),
        Entry(char: "🚑", name: "ambulance"),
        Entry(char: "🚒", name: "fire engine truck"),
        Entry(char: "🚲", name: "bicycle bike"),
        Entry(char: "🛵", name: "scooter moped"),
        Entry(char: "🏍️", name: "motorcycle bike"),
        Entry(char: "🚆", name: "train rail"),
        Entry(char: "🚇", name: "metro subway"),
        Entry(char: "✈️", name: "airplane flight travel plane"),
        Entry(char: "🚀", name: "rocket launch ship deploy fast space"),
        Entry(char: "🛸", name: "flying saucer ufo"),
        Entry(char: "🚁", name: "helicopter"),
        Entry(char: "⛵", name: "sailboat sailing"),
        Entry(char: "🚢", name: "ship cruise"),
        Entry(char: "⚓", name: "anchor"),
        Entry(char: "🗺️", name: "world map travel"),
        Entry(char: "🧭", name: "compass navigate"),
        Entry(char: "🏔️", name: "mountain snow peak"),
        Entry(char: "🏖️", name: "beach umbrella vacation"),
        Entry(char: "🏝️", name: "desert island"),
        Entry(char: "🏕️", name: "camping tent"),
        Entry(char: "🏠", name: "house home"),
        Entry(char: "🏢", name: "office building work"),
        Entry(char: "🏥", name: "hospital"),
        Entry(char: "🏦", name: "bank money"),
        Entry(char: "🏫", name: "school"),
        Entry(char: "⛩️", name: "shinto shrine"),
        Entry(char: "🕌", name: "mosque"),
        Entry(char: "⛪", name: "church"),
        Entry(char: "🛕", name: "hindu temple"),
        Entry(char: "🗼", name: "tokyo tower"),
        Entry(char: "🗽", name: "statue of liberty new york"),
        Entry(char: "🌉", name: "bridge night"),
        Entry(char: "🌅", name: "sunrise"),
        Entry(char: "🌇", name: "sunset city"),
        Entry(char: "🌃", name: "night city stars"),
        // Nature and weather
        Entry(char: "☀️", name: "sun sunny"),
        Entry(char: "🌤️", name: "sun small cloud"),
        Entry(char: "⛅", name: "sun behind cloud partly"),
        Entry(char: "☁️", name: "cloud cloudy"),
        Entry(char: "🌧️", name: "rain cloud"),
        Entry(char: "⛈️", name: "thunderstorm lightning rain"),
        Entry(char: "🌩️", name: "lightning cloud"),
        Entry(char: "❄️", name: "snowflake cold snow"),
        Entry(char: "☃️", name: "snowman snow"),
        Entry(char: "🌬️", name: "wind face blowing"),
        Entry(char: "🌪️", name: "tornado"),
        Entry(char: "🌈", name: "rainbow pride"),
        Entry(char: "🌊", name: "wave ocean water sea"),
        Entry(char: "🌙", name: "crescent moon night"),
        Entry(char: "🌕", name: "full moon"),
        Entry(char: "⭐", name: "star"),
        Entry(char: "🌟", name: "glowing star sparkle"),
        Entry(char: "✨", name: "sparkles shiny magic new"),
        Entry(char: "☄️", name: "comet"),
        Entry(char: "🌍", name: "earth globe world africa europe"),
        Entry(char: "🌎", name: "earth globe world americas"),
        Entry(char: "🪐", name: "saturn planet rings"),
        Entry(char: "🌱", name: "seedling sprout plant grow"),
        Entry(char: "🌲", name: "evergreen tree pine"),
        Entry(char: "🌳", name: "deciduous tree"),
        Entry(char: "🌴", name: "palm tree tropical"),
        Entry(char: "🌵", name: "cactus desert"),
        Entry(char: "🍀", name: "four leaf clover luck lucky"),
        Entry(char: "🍁", name: "maple leaf autumn canada"),
        Entry(char: "🍂", name: "fallen leaves autumn"),
        Entry(char: "🌸", name: "cherry blossom sakura flower"),
        Entry(char: "🌹", name: "rose flower"),
        Entry(char: "🌻", name: "sunflower"),
        Entry(char: "🌷", name: "tulip flower"),
        Entry(char: "💐", name: "bouquet flowers"),
        Entry(char: "🔥", name: "fire flame hot lit"),
        Entry(char: "💧", name: "droplet water drop"),
        Entry(char: "⚡", name: "zap lightning bolt electric fast"),
        // Objects and tech
        Entry(char: "💻", name: "laptop computer mac"),
        Entry(char: "🖥️", name: "desktop computer imac monitor"),
        Entry(char: "⌨️", name: "keyboard typing"),
        Entry(char: "🖱️", name: "mouse computer"),
        Entry(char: "🖨️", name: "printer print"),
        Entry(char: "📱", name: "phone iphone mobile smartphone"),
        Entry(char: "☎️", name: "telephone old phone"),
        Entry(char: "📞", name: "phone receiver call"),
        Entry(char: "🔋", name: "battery power"),
        Entry(char: "🪫", name: "low battery drained"),
        Entry(char: "🔌", name: "plug electric power"),
        Entry(char: "💾", name: "floppy disk save"),
        Entry(char: "💿", name: "cd disc"),
        Entry(char: "📀", name: "dvd disc"),
        Entry(char: "🧮", name: "abacus calculate"),
        Entry(char: "🎥", name: "movie camera film"),
        Entry(char: "📷", name: "camera photo"),
        Entry(char: "📸", name: "camera flash photo"),
        Entry(char: "📹", name: "video camera"),
        Entry(char: "🔍", name: "magnifying glass search left"),
        Entry(char: "🔎", name: "magnifying glass search right"),
        Entry(char: "💡", name: "bulb idea light"),
        Entry(char: "🔦", name: "flashlight torch"),
        Entry(char: "🕯️", name: "candle"),
        Entry(char: "📖", name: "open book read"),
        Entry(char: "📚", name: "books stack study"),
        Entry(char: "📓", name: "notebook"),
        Entry(char: "📝", name: "memo note pencil write"),
        Entry(char: "✏️", name: "pencil write"),
        Entry(char: "🖊️", name: "pen ballpoint"),
        Entry(char: "🖋️", name: "fountain pen"),
        Entry(char: "📌", name: "pushpin pin"),
        Entry(char: "📍", name: "round pushpin location pin"),
        Entry(char: "📎", name: "paperclip attach"),
        Entry(char: "📏", name: "ruler straight"),
        Entry(char: "✂️", name: "scissors cut"),
        Entry(char: "📦", name: "package box shipping"),
        Entry(char: "📫", name: "mailbox mail"),
        Entry(char: "📧", name: "email envelope mail"),
        Entry(char: "✉️", name: "envelope letter mail"),
        Entry(char: "📤", name: "outbox send"),
        Entry(char: "📥", name: "inbox receive"),
        Entry(char: "📅", name: "calendar date"),
        Entry(char: "📆", name: "tear off calendar"),
        Entry(char: "🗓️", name: "spiral calendar schedule"),
        Entry(char: "📈", name: "chart increasing up growth stonks"),
        Entry(char: "📉", name: "chart decreasing down loss"),
        Entry(char: "📊", name: "bar chart statistics data"),
        Entry(char: "🗂️", name: "card index dividers files"),
        Entry(char: "📁", name: "folder file"),
        Entry(char: "📂", name: "open folder file"),
        Entry(char: "🗑️", name: "wastebasket trash delete"),
        Entry(char: "🔒", name: "locked padlock secure"),
        Entry(char: "🔓", name: "unlocked open"),
        Entry(char: "🔑", name: "key password"),
        Entry(char: "🗝️", name: "old key"),
        Entry(char: "🔨", name: "hammer build fix"),
        Entry(char: "🪛", name: "screwdriver"),
        Entry(char: "🔧", name: "wrench tool fix settings"),
        Entry(char: "⚙️", name: "gear settings config cog"),
        Entry(char: "🧲", name: "magnet attract"),
        Entry(char: "🧪", name: "test tube experiment science"),
        Entry(char: "🧬", name: "dna genetics"),
        Entry(char: "🔬", name: "microscope science"),
        Entry(char: "🔭", name: "telescope astronomy"),
        Entry(char: "💊", name: "pill medicine drug"),
        Entry(char: "💉", name: "syringe injection vaccine"),
        Entry(char: "🩹", name: "bandage band aid"),
        Entry(char: "🧹", name: "broom sweep clean"),
        Entry(char: "🧺", name: "basket laundry"),
        Entry(char: "🧻", name: "toilet paper roll"),
        Entry(char: "🛒", name: "shopping cart trolley"),
        Entry(char: "💰", name: "money bag rich"),
        Entry(char: "💸", name: "money wings flying spend"),
        Entry(char: "💵", name: "dollar banknote cash"),
        Entry(char: "💳", name: "credit card payment"),
        Entry(char: "🪙", name: "coin money"),
        Entry(char: "💎", name: "gem diamond jewel"),
        Entry(char: "⚖️", name: "balance scale justice law"),
        Entry(char: "🧯", name: "fire extinguisher"),
        Entry(char: "🛡️", name: "shield protect security"),
        Entry(char: "🗡️", name: "dagger sword"),
        Entry(char: "🏹", name: "bow and arrow archer"),
        Entry(char: "🪃", name: "boomerang"),
        Entry(char: "🎃", name: "jack o lantern pumpkin halloween"),
        Entry(char: "🎄", name: "christmas tree"),
        Entry(char: "🧨", name: "firecracker dynamite"),
        Entry(char: "🎆", name: "fireworks"),
        Entry(char: "🧸", name: "teddy bear toy"),
        Entry(char: "🪄", name: "magic wand"),
        Entry(char: "🔮", name: "crystal ball fortune"),
        Entry(char: "🧿", name: "nazar amulet evil eye"),
        Entry(char: "🕰️", name: "mantelpiece clock time"),
        Entry(char: "⏰", name: "alarm clock wake"),
        Entry(char: "⏱️", name: "stopwatch timer"),
        Entry(char: "⌛", name: "hourglass done time"),
        Entry(char: "⏳", name: "hourglass flowing time waiting"),
        // Symbols
        Entry(char: "✅", name: "check mark button done yes green"),
        Entry(char: "✔️", name: "check mark done yes"),
        Entry(char: "❌", name: "cross mark x no wrong"),
        Entry(char: "❎", name: "cross mark button no"),
        Entry(char: "➕", name: "plus add"),
        Entry(char: "➖", name: "minus subtract"),
        Entry(char: "➗", name: "divide division"),
        Entry(char: "✖️", name: "multiply multiplication x"),
        Entry(char: "♾️", name: "infinity forever"),
        Entry(char: "‼️", name: "double exclamation important"),
        Entry(char: "⁉️", name: "exclamation question interrobang"),
        Entry(char: "❓", name: "question mark red"),
        Entry(char: "❗", name: "exclamation mark red"),
        Entry(char: "⚠️", name: "warning caution alert"),
        Entry(char: "🚫", name: "prohibited no forbidden"),
        Entry(char: "🔞", name: "no one under eighteen"),
        Entry(char: "☢️", name: "radioactive nuclear"),
        Entry(char: "☣️", name: "biohazard"),
        Entry(char: "🔴", name: "red circle"),
        Entry(char: "🟠", name: "orange circle"),
        Entry(char: "🟡", name: "yellow circle"),
        Entry(char: "🟢", name: "green circle"),
        Entry(char: "🔵", name: "blue circle"),
        Entry(char: "🟣", name: "purple circle"),
        Entry(char: "⚫", name: "black circle"),
        Entry(char: "⚪", name: "white circle"),
        Entry(char: "🔺", name: "red triangle up"),
        Entry(char: "🔻", name: "red triangle down"),
        Entry(char: "🔶", name: "orange diamond large"),
        Entry(char: "🔷", name: "blue diamond large"),
        Entry(char: "🆗", name: "ok button"),
        Entry(char: "🆕", name: "new button"),
        Entry(char: "🆒", name: "cool button"),
        Entry(char: "🆓", name: "free button"),
        Entry(char: "🔠", name: "input latin uppercase abcd"),
        Entry(char: "🔢", name: "input numbers 1234"),
        Entry(char: "#️⃣", name: "hash keycap number"),
        Entry(char: "*️⃣", name: "asterisk keycap"),
        Entry(char: "▶️", name: "play button"),
        Entry(char: "⏸️", name: "pause button"),
        Entry(char: "⏹️", name: "stop button"),
        Entry(char: "⏺️", name: "record button"),
        Entry(char: "⏭️", name: "next track skip"),
        Entry(char: "⏮️", name: "previous track"),
        Entry(char: "🔀", name: "shuffle tracks"),
        Entry(char: "🔁", name: "repeat loop"),
        Entry(char: "🔊", name: "speaker high volume loud"),
        Entry(char: "🔇", name: "muted speaker silence"),
        Entry(char: "🔔", name: "bell notification"),
        Entry(char: "🔕", name: "bell slash no notification silent"),
        Entry(char: "📢", name: "loudspeaker announcement"),
        Entry(char: "📣", name: "megaphone cheering"),
        Entry(char: "🔗", name: "link chain url"),
        Entry(char: "♻️", name: "recycle recycling"),
        Entry(char: "⚜️", name: "fleur de lis"),
        Entry(char: "🔱", name: "trident emblem"),
        Entry(char: "🕉️", name: "om hindu"),
        Entry(char: "☮️", name: "peace symbol"),
        Entry(char: "🛐", name: "place of worship"),
        Entry(char: "🇮🇳", name: "flag india"),
        Entry(char: "🇺🇸", name: "flag usa united states america"),
        Entry(char: "🇬🇧", name: "flag uk united kingdom britain"),
        Entry(char: "🇯🇵", name: "flag japan"),
        Entry(char: "🇩🇪", name: "flag germany"),
        Entry(char: "🇫🇷", name: "flag france"),
        Entry(char: "🇨🇦", name: "flag canada"),
        Entry(char: "🇦🇺", name: "flag australia"),
        Entry(char: "🇸🇬", name: "flag singapore"),
        Entry(char: "🇦🇪", name: "flag uae emirates dubai"),
        Entry(char: "🏳️", name: "white flag surrender"),
        Entry(char: "🏴", name: "black flag"),
        Entry(char: "🏁", name: "checkered flag finish race done"),
        Entry(char: "🚩", name: "red flag warning triangular"),
        // People and roles
        Entry(char: "👶", name: "baby infant"),
        Entry(char: "👦", name: "boy kid"),
        Entry(char: "👧", name: "girl kid"),
        Entry(char: "🧑", name: "person adult"),
        Entry(char: "👨", name: "man male"),
        Entry(char: "👩", name: "woman female"),
        Entry(char: "🧓", name: "older person elderly"),
        Entry(char: "👨‍💻", name: "man technologist developer coder programmer"),
        Entry(char: "👩‍💻", name: "woman technologist developer coder programmer"),
        Entry(char: "🧑‍🎓", name: "student graduate"),
        Entry(char: "🧑‍🏫", name: "teacher professor"),
        Entry(char: "🧑‍⚕️", name: "health worker doctor nurse"),
        Entry(char: "🧑‍🍳", name: "cook chef"),
        Entry(char: "🧑‍🔧", name: "mechanic"),
        Entry(char: "🧑‍🚀", name: "astronaut space"),
        Entry(char: "🕵️", name: "detective spy investigate"),
        Entry(char: "💂", name: "guard"),
        Entry(char: "🥷", name: "ninja stealth"),
        Entry(char: "🦸", name: "superhero"),
        Entry(char: "🦹", name: "supervillain"),
        Entry(char: "🧙", name: "mage wizard"),
        Entry(char: "🧛", name: "vampire"),
        Entry(char: "🏃", name: "runner running run"),
        Entry(char: "🚶", name: "walking person walk"),
        Entry(char: "🧘", name: "lotus position meditate yoga"),
        Entry(char: "🏋️", name: "weight lifting gym workout"),
        Entry(char: "🚴", name: "cyclist biking"),
        Entry(char: "🏊", name: "swimmer swimming"),
        Entry(char: "🤷", name: "shrug dunno whatever"),
        Entry(char: "🤦", name: "facepalm smh"),
        Entry(char: "💁", name: "tipping hand sassy information"),
        Entry(char: "🙋", name: "raising hand volunteer me"),
        Entry(char: "👪", name: "family"),
        Entry(char: "👫", name: "couple holding hands"),
    ]
}
